swagger: "2.0"
info:
  description: "Simple API to manage posts"
  version: "1.0.0"
  title: "posts API"
host: "localhost:3000"
basePath: "/"
consumes:
- "application/json"
produces:
- "application/json"
tags:
- name: "post"
  description: "operations on posts"
paths:
  /posts:
    get:
      tags:
      - "post"
      summary: "Get a list of posts"
      description: ""
      parameters: 
      - in: "query"
        name: "page"
        description: "The wanted page number"
        type: 'number'
      - in: "query"
        name: "per_page"
        description: "The number of items per page"
        type: 'number'
      headers:
        content-range: 
          schema:
            type: string
            example: "1-10/10"
            description: "<range begin>-<range stop>/<total items count>"
      responses:
        "200":
          description: "OK"
          schema:
            type: 'array'
            items: 
              $ref: '#/definitions/post'
    post:
      tags:
      - "post"
      summary: "Add a new post"
      description: ""
      parameters:
      - in: "body"
        name: "post"
        description: "post object that needs to be added in DB"
        required: true
        schema:
          allOf:
           - $ref: "#/definitions/postEditableAttributes"
           - type: 'object'
             required:
              - "name"
      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/post"
        "422":
          $ref: '#/responses/unprocessableEntity'
        "409":
          $ref: '#/responses/conflict'
  /posts/{postId}:
    put:
      tags:
      - "post"
      summary: "Update an existing post"
      description: ""
      parameters:
      - name: "postId"
        in: "path"
        description: "ID of post to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "post"
        description: "post object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/postEditableAttributes"
      responses:
        "200":
          description: "Updated"
          schema:
            $ref: "#/definitions/post"       
        "404":
          $ref: '#/responses/notFound'
        "409":
          $ref: '#/responses/conflict'
        "422":
          $ref: '#/responses/unprocessableEntity'
responses:
  notFound:
    description: Not found
    schema:
      $ref: '#/definitions/genericError'
  unprocessableEntity:
    description: The provided data is not valid
    schema:
      $ref: '#/definitions/genericError'
  conflict:
    description: Some information is not allowed to be duplicated
    schema:
      $ref: '#/definitions/genericError'

definitions:
  genericError:
    type: 'object'
    properties: 
      errorMessage: 
        type: "string"
      errorDetails: 
        type: "array"
        items: 
          type: 'object'

  postEditableAttributes:
    type: "object"
    properties:
      name:
        type: "string"
        example: "do something"
      done: 
        type: "boolean"

  post:
    allOf: 
      - type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
      - $ref: '#/definitions/postEditableAttributes'
      